server:
  port: 6001
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/bit_monitor?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 1000ms # 连接超时时间
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
logging:
  file:
    path: ./logs
    max-history: 30
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
# 钉钉机器人推送
ding-talk:
  enable: false # 是否开启钉钉推送
  keyword: 前端监控报警平台 # 钉钉推送的关键词
